### ISSUE TITLE
运行Balance.transfer时报错“Invalid Transaction”

### ISSUE THREAD

**Issue by yasyzb** [JFJun/stafi-substrate-go#1]
你好，运行reademe中Balance.transfer例子时报错“Invalid Transaction”
specVersion: 26
transactionVersion: 5

**Comment by JFJun** [comment]
可以给我看一下你的代码吗

**Comment by JFJun** [comment]
> 你好，运行reademe中Balance.transfer例子时报错“Invalid Transaction”
> specVersion: 26
> transactionVersion: 5

有可能是因为你的地址的钱不够造成的，如果你的地址的金额小于 1+手续费+转账金额，就会抱这个错误，当然还有其他的原因呢

**Comment by yasyzb** [comment]
```
package main

import (
	"fmt"
	"log"

	"github.com/JFJun/go-substrate-crypto/crypto"
	"github.com/JFJun/go-substrate-crypto/ss58"
	"github.com/JFJun/stafi-substrate-go/client"
	"github.com/JFJun/stafi-substrate-go/expand"
	"github.com/JFJun/stafi-substrate-go/tx"
	"github.com/stafiprotocol/go-substrate-rpc-client/types"
)

const seed = "0xd2e130bce4f31011c41e5690df610f0138f89fb391ce0e25298ba7379a32ddba"
const from = "12HFf1Cgex3gWEBoo1cGShzM6mEjK5HkZgpjaKRJgcZzgNzF"
const to = from
const amount = uint64(12345)
const mainnet = "http://xxx:9933"

func main() {
	c, err := client.New(mainnet)
	if err != nil {
		log.Fatal("new client: ", err)
	}
	c.SetPrefix(ss58.PolkadotPrefix)

	v, err := c.C.RPC.State.GetRuntimeVersionLatest()
	if err != nil {
		log.Fatal("GetRuntimeVersionLatest: ", err)
	}
	// fmt.Println(v.SpecVersion, v.TransactionVersion)

	// fromInfo, err := c.GetAccountInfo(from)
	// if err != nil {
	// 	log.Fatal("GetAccountInfo", err)
	// }
	nonce := uint64(0)
	// if fromInfo != nil {
	// 	nonce = uint64(fromInfo.Nonce)
	// }
	types.SetSerDeOptions(types.SerDeOptions{NoPalletIndices: true})
	transaction := tx.CreateTransaction(from, to, amount, nonce)

	block, err := c.C.RPC.Chain.GetBlockLatest()
	if err != nil {
		log.Fatal("GetBlockLatest: ", err)
	}
	blockHash, err := c.C.RPC.Chain.GetBlockHash(uint64(block.Block.Header.Number))
	if err != nil {
		log.Fatal("GetBlockHash: ", err)
	}
	// fmt.Println("c.GetGenesisHash()", c.GetGenesisHash())
	// fmt.Printf("%s, %d", blockHash.Hex(), block.Block.Header.Number)
	transaction.SetGenesisHashAndBlockHash(c.GetGenesisHash(), blockHash.Hex())

	ed, err := expand.NewMetadataExpand(c.Meta)
	if err != nil {
		log.Fatal(err)
	}
	btCall, err := ed.MV.GetCallIndex("Balances", "transfer")
	if err != nil {
		log.Fatal("GetCallIndex: ", err)
	}

	transaction.SetSpecVersionAndCallId(uint32(v.SpecVersion), uint32(v.TransactionVersion), btCall)
	signed, err := transaction.SignTransaction(seed, crypto.Sr25519Type)
	if err != nil {
		log.Fatal("SignTransaction: ", err)
	}
	// fmt.Println(signed)

	var result interface{}
	err = c.C.Client.Call(&result, "author_submitExtrinsic", signed)
	if err != nil {
		log.Fatal("author_submitExtrinsic: ", err)
	}

	fmt.Println(result)
}

```

**Comment by JFJun** [comment]
> mainnet

私钥就别发出来了呀，你的这个地址没有钱

**Comment by yasyzb** [comment]
> > mainnet
> 
> 私钥就别发出来了呀，你的这个地址没有钱

原来是这样，尴尬

**Comment by yasyzb** [comment]
> > mainnet
> 
> 私钥就别发出来了呀，你的这个地址没有钱

我还想请教一个问题，交易的手续费可以提前计算出来么？

**Comment by JFJun** [comment]
> > > mainnet
> > 
> > 
> > 私钥就别发出来了呀，你的这个地址没有钱
> 
> 我还想请教一个问题，交易的手续费可以提前计算出来么？

手续费是不可以提前计算的，波卡的手续费是通过时间来动态调整的，需要等你的交易上链以后才能计算

**Comment by yasyzb** [comment]
> > > > mainnet
> > > 
> > > 
> > > 私钥就别发出来了呀，你的这个地址没有钱
> > 
> > 
> > 我还想请教一个问题，交易的手续费可以提前计算出来么？
> 
> 手续费是不可以提前计算的，波卡的手续费是通过时间来动态调整的，需要等你的交易上链以后才能计算

谢谢。我再请教一个问题，https://github.com/paritytech/txwrapper/blob/master/examples/polkadot.ts#L67，parity的js库中，构建交易时多两个字段：eraPeriod和blockNumber，而您的例子中没有这两个字段？

**Comment by JFJun** [comment]
> > > > > mainnet
> > > > 
> > > > 
> > > > 私钥就别发出来了呀，你的这个地址没有钱
> > > 
> > > 
> > > 我还想请教一个问题，交易的手续费可以提前计算出来么？
> > 
> > 
> > 手续费是不可以提前计算的，波卡的手续费是通过时间来动态调整的，需要等你的交易上链以后才能计算
> 
> 谢谢。我再请教一个问题，https://github.com/paritytech/txwrapper/blob/master/examples/polkadot.ts#L67, parity的js库中，构建交易时多两个字段：eraPeriod和blockNumber，而您的例子中没有找到这两个字段？
> 我们在使用您的库时，需要填上这两个字段么？

这两个参数主要是为了保证你的交易如果一直没有上链的话能存在多少个块中，如果超过（默认64个）这个块数，交易失败。我目前设置的era是0，就是一直不回退，就目前dot的转账来说不算拥挤，所以不需要设置。等后续如果真需要，但时候在添加上去

**Comment by yasyzb** [comment]
> > > > > > mainnet
> > > > > 
> > > > > 
> > > > > 私钥就别发出来了呀，你的这个地址没有钱
> > > > 
> > > > 
> > > > 我还想请教一个问题，交易的手续费可以提前计算出来么？
> > > 
> > > 
> > > 手续费是不可以提前计算的，波卡的手续费是通过时间来动态调整的，需要等你的交易上链以后才能计算
> > 
> > 
> > 谢谢。我再请教一个问题，https://github.com/paritytech/txwrapper/blob/master/examples/polkadot.ts#L67, parity的js库中，构建交易时多两个字段：eraPeriod和blockNumber，而您的例子中没有找到这两个字段？
> > 我们在使用您的库时，需要填上这两个字段么？
> 
> 这两个参数主要是为了保证你的交易如果一直没有上链的话能存在多少个块中，如果超过（默认64个）这个块数，交易失败。我目前设置的era是0，就是一直不回退，就目前dot的转账来说不算拥挤，所以不需要设置。等后续如果真需要，但时候在添加上去

非常感谢您
