### ISSUE TITLE
decode event data error: unable to find field Claims_Claimed for event #9 with EventID [24 0]

### ISSUE THREAD

**Issue by polariseye** [JFJun/stafi-substrate-go#3]
运行dot时，有时会报这个错，我该如何处理，如果需要自己实现的话，该如何实现
decode event data error: unable to find field Claims_Claimed for event #9 with EventID [24 0]

**Comment by JFJun** [comment]
> Claims_Claimed

可以把报错的区块高度给我吗，我检查一下

**Comment by polariseye** [comment]
出错的区块高度是 3222261。是dot的链。但是我dot的事件只会暂存最近几个区块的。所以你无法用这个区块重现。我在想是不是最近dot新增了事件
