### ISSUE TITLE
decode tip error: Cannot read the required number of bytes 67, only 32 available

### ISSUE THREAD

**Issue by polariseye** [JFJun/stafi-substrate-go#5]
解码chainx链时出错，报:decode tip error: Cannot read the required number of bytes 67, only 32 available
chainx地址:wss://mainnet.chainx.org/ws
区块高度:792316
测试代码:
var c, err = client.New("wss://mainnet.chainx.org/ws")
	if err != nil {
		fmt.Println(err.Error())
		return
	}

	respObj, err := c.GetBlockByNumber(792316)
	if err != nil {
		fmt.Println(err.Error())
		return
	}

	fmt.Println("ok:", respObj)

**Comment by JFJun** [comment]
> 792316
如果你是用的是最新的包，需要设置expand.SetSerDeOptions(false)，如果用的久的包，需要设置types.SetSerDeOptions(types.SerDeOptions{NoPalletIndices: true})，这样就可以了

**Comment by JFJun** [comment]
> 解码chainx链时出错，报:decode tip error: Cannot read the required number of bytes 67, only 32 available
> chainx地址:wss://mainnet.chainx.org/ws
> 区块高度:792316
> 测试代码:
> var c, err = client.New("wss://mainnet.chainx.org/ws")
> if err != nil {
> fmt.Println(err.Error())
> return
> }
> 
> ```
> respObj, err := c.GetBlockByNumber(792316)
> if err != nil {
> 	fmt.Println(err.Error())
> 	return
> }
> 
> fmt.Println("ok:", respObj)
> ```

如果你是用的是最新的包，需要设置expand.SetSerDeOptions(false)，如果用的旧的包，需要设置types.SetSerDeOptions(types.SerDeOptions{NoPalletIndices: false})，这样就可以了
