### ISSUE TITLE
你好，polkadot发送交易失败了

### ISSUE THREAD

**Issue by yasyzb** [JFJun/stafi-substrate-go#7]
polkadot的runtime又升级了，可以麻烦升级适配一下吗？感谢

报错：
submit transaction fail: submit transaction failed: Verification Error: Runtime error: Execution failed: Wasmi(Trap(Trap{ kind: Unreachable }))

**Comment by JFJun** [comment]
> polkadot的runtime又升级了，可以麻烦升级适配一下吗？感谢
> 
> 报错：
> submit transaction fail: submit transaction failed: Verification Error: Runtime error: Execution failed: Wasmi(Trap(Trap{ kind: Unreachable }))

我把这次dot的升级转到另外一个包了，https://github.com/JFJun/bifrost-go.git (v1.0.1)。新的这个包和当前包是一样的，只不过解决了这次polkadot升级的问题。交易的可以参考https://github.com/JFJun/bifrost-go/test/tx_test.go。
